# Generated by Django 3.2.9 on 2021-11-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sales'),
        ),
    ]
