# Generated by Django 3.2.9 on 2021-12-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211203_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.support'),
        ),
    ]
