# Generated by Django 3.2.9 on 2021-12-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_event_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.sales'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contract'),
        ),
    ]
