# Generated by Django 3.2.9 on 2021-12-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211205_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sales'),
        ),
    ]
